language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew uninstall openssl            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl --universal  ; fi
script:
  - cargo build
  - cargo test
env:
  osx:
    - OPENSSL_INCLUDE_DIR: /usr/local/opt/openssl/include
    - OPENSSL_LIB_DIR: /usr/local/opt/openssl/lib
os:
  - linux
  - osx
